In [1]:
# Q.1 Create a 3×3 NumPy array of all True.

import numpy as np

In [4]:
arr = np.array(range(1,10)).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:

arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
# Q.2 Create a 1D array of 10 evenly spaced values between 5 and 50.
arr = np.arange(5,51,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [12]:
# Q.3 Write a code to compute the dot product of two NumPy arrays.
A = np.array([2,3,4,5])
B=np.array([7,8,9,4])
print(A)
print(B)

dt = np.dot(A,B)
print(dt)

[2 3 4 5]
[7 8 9 4]
94


In [17]:
# Q.4 Create 4 ×4 Identity Matrix,and replace the diagonal value with 12.
arr = np.eye(4,4, dtype = int)
np.fill_diagonal(arr, 12)
arr

array([[12,  0,  0,  0],
       [ 0, 12,  0,  0],
       [ 0,  0, 12,  0],
       [ 0,  0,  0, 12]])

In [18]:
# Q.5 Write a code to edit the value 40 by 400 in given 1D array
# Input: A=[20,30,40,50,60]
A = np.array([20,30,40,50,60])
print(A)
A[2] = 400
print(A)

[20 30 40 50 60]
[ 20  30 400  50  60]


In [19]:
A[A == 40] = 400
print(A)

[ 20  30 400  50  60]


In [22]:
A = np.where(A == 40,400, A)
print(A)

[400 400 400 400 400]


In [23]:
A = np.where(A == 40, 400, A)
print(A)

[400 400 400 400 400]


In [24]:
A = np.array([20, 30, 40, 50, 60])  # Fresh array
print(A)  # [20 30 40 50 60]

A = np.where(A == 40, 400, A)
print(A)

[20 30 40 50 60]
[ 20  30 400  50  60]


In [30]:
# Q.6 Write a code to update the each value by it’s square in given 2D
# array
# Input: A=[[20,30],[40,50],[60,70]]
arr = np.array([[20,30],[40,50],[60,70]])
print(arr)

[[20 30]
 [40 50]
 [60 70]]


In [31]:
np.square(arr)

array([[ 400,  900],
       [1600, 2500],
       [3600, 4900]])

In [34]:
# Q.7 Write a code to delete 50 in given 1D array.
# Input: A=[20,30,40,50,60]
A = np.array([20,30,40,50])
print(A)
A = np.delete(A, np.where(A==30))
print(A)

[20 30 40 50]
[20 40 50]


In [35]:
# Q.8 Write a code to insert 48 in 3 rd indexing in given 1D array.
# Input: A=[20,30,40,50,60]
A = np.array([20,30,40,50,60])
A[3] = 48
print(A)

[20 30 40 48 60]


In [38]:
# Q.9 Write a code to find odd number in given 1D array.
# Input: A=[20,3,7,80,89]
A = np.array([20,3,7,80,89])
print(A)
np.where(A % 2 != 0)

[20  3  7 80 89]


(array([1, 2, 4]),)

In [41]:
odd = np.where(A % 2 != 0)
print(A[odd])

[ 3  7 89]


In [48]:
# Q.10 Write a code to replace 0 by 99 in identity matrix.
arr = np.eye(3, dtype = int)
print(arr)
print()
a = np.where(arr == 0, 99, arr)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[ 1 99 99]
 [99  1 99]
 [99 99  1]]
