In [2]:
import numpy as np


In [3]:
# Q.1 Write a NumPy program to create an array of integers from 30 to 70.

arr1 = np.arange(30,71)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [4]:
# Q.2 Write a NumPy program to create an array of all even integers from
# 40 to 139.

arr2 = np.arange(40,140,2)
arr2

array([ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,
        66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,
        92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112, 114, 116,
       118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138])

In [8]:
# Q.3 Write a NumPy program to create an array of 10 zeros, 10 ones, and
# 10 fives.

zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)

print(zeros)
print(ones)
print(fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [10]:
# Q.4 Write a NumPy program to create a 3x3 identity matrix.

identity = np.eye(3, dtype = int)
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [14]:
# Write a NumPy program to create a given matrix.

arr3 = np.arange(1,21)
arr3
arr3.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
# Q.6 Write a NumPy program to print above matrix in reverse order.(20 to
# 1)

arr4 = np.arange(20,0,-1)
print(arr4)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [21]:
# Write a program to pick any 3 random values from 100 to 300.

rd = np.random.randint(100,300,3)
print(rd)

[139 123 179]


In [25]:
# Q.8 Write a program to pick any random three names from given List

A=['SACHIN','VIRAT','DHONI','ROHIT','DRAVID','GANGOLY']

a = np.array(A)
rd = np.random.choice(a,3)
print(rd)





['GANGOLY' 'DRAVID' 'ROHIT']
