In [1]:
import numpy as np

In [5]:
p = [34,2,5,6]
p

[34, 2, 5, 6]

In [6]:
print(type(p))

<class 'list'>


In [7]:
A = np.array(p)
print(A)
print(type(A))

[34  2  5  6]
<class 'numpy.ndarray'>


In [8]:
a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
a = np.array(range(1,10,2))
print(a)

[1 3 5 7 9]


In [11]:
print(a.ndim)

1


In [3]:
# 2/6/2026

In [4]:
import numpy as np


In [6]:
a1 = np.array([10,20,30,40,50])
a2 = np.array([100,200,300,400,500])
print(a1)
print(a2)

[10 20 30 40 50]
[100 200 300 400 500]


In [7]:
print("size 0f a1", a1.size)

size 0f a1 5


In [8]:
k = np.concatenate((a1,a2))
print(k)

[ 10  20  30  40  50 100 200 300 400 500]


In [9]:
a1 = np.array([10,20,30,40,50])
a2 = np.array([100,200,300,400,500])
h = np.hstack((a1,a2))
print(h)

[ 10  20  30  40  50 100 200 300 400 500]


In [10]:
v = np.vstack((a1,a2))
print(v)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [12]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[100,200],[300,400]])
print(a1)
print()
print(a2)

[[10 20]
 [30 40]]

[[100 200]
 [300 400]]


In [13]:
k1 = np.hstack((a1,a2))
print(k1)

[[ 10  20 100 200]
 [ 30  40 300 400]]


In [14]:
v2 = np.vstack((a1,a2))
print(v2)

[[ 10  20]
 [ 30  40]
 [100 200]
 [300 400]]


In [16]:
k2 = np.concatenate((a1,a2))
print(k2)

[[ 10  20]
 [ 30  40]
 [100 200]
 [300 400]]


In [18]:
x  = np.array([[1,2,3,4]])
print(x.ndim)

2


In [19]:
y = x.flatten()
print(y)
print(y.ndim)

[1 2 3 4]
1


In [20]:
y = np.append(y,10)
print(y)

[ 1  2  3  4 10]


In [21]:
print(x)

[[1 2 3 4]]


In [22]:
z = x.ravel()
print(z)
print(z.ndim)

[1 2 3 4]
1


In [23]:
z = np.append(z,10)
print(z)

[ 1  2  3  4 10]


In [25]:
x = np.array([[10,20,30,40,50]])
print(x)
f1 = x.ravel()
print(f1)
f1[1] = 200
print(f1)
print(x)

[[10 20 30 40 50]]
[10 20 30 40 50]
[ 10 200  30  40  50]
[[ 10 200  30  40  50]]


In [26]:
# copy and view function
s1 = np.array([[1,2,3,4,5]])
print(s1)
s2 = s1.copy()
print(s2)

[[1 2 3 4 5]]
[[1 2 3 4 5]]


In [ ]:
s2 = s1.view()
print(s2)

In [2]:
#view

A = np.array([10,20,30,40,50])
print(A)



[10 20 30 40 50]


In [3]:
v = A.view()
print(v)

[10 20 30 40 50]


In [4]:
v[2] = 900
print(v)
print(A)

[ 10  20 900  40  50]
[ 10  20 900  40  50]


In [5]:
A[3] = 1000
print(A)
print(v)

[  10   20  900 1000   50]
[  10   20  900 1000   50]


In [7]:

A = np.array([10,20,30,40])
B = np.array([4,5,6,7])
np.dot(A,B)

x = np.array([10,20,30])
y = np.array([4,5,6])
np.cross(x,y)

x1 = np.array([[1,2],[3,4]])
y1 = np.array([[4,5],[2,3]])
x1 @ y1


array([[ 8, 11],
       [20, 27]])

In [8]:
A = np.array([10,2,30,4,5,7,90,21,34])
k = np.where(A>5)
print(k)

(array([0, 2, 5, 6, 7, 8]),)
