In [1]:
import numpy as np

In [3]:
# Q. 1 Extract the first four columns of this 2-D array
arr = np.array([[0,1,2,3],
                [20,21,22,23],
                [40,41,42,43],
                [60,61,62,63],
                [80,81,82,83]])


In [6]:
print(arr)

print(arr[::,0:3])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
[[ 0  1  2]
 [20 21 22]
 [40 41 42]
 [60 61 62]
 [80 81 82]]


In [10]:
# Q.2 How to add a border (filled with 0's) around an existing array?
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(bordered_arr)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [11]:
# Q.3 Create a 4*4 Matrix with 1 on the border and 0 inside.

matrix = np.ones((4, 4), dtype=int)

# 2. Set the interior elements (from index 1 up to, but not including, the last index) to 0
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [14]:
# Q.4 How to find common values between two arrays?
arr1 = np.arange(1,6)
arr2 = np.array([10,2,5,22,55])
print(arr1)
print(arr2)

[1 2 3 4 5]
[10  2  5 22 55]


In [15]:
cm = np.intersect1d(arr1,arr2)
print(cm)

[2 5]


In [17]:
# Q.5 Subtract the mean of each row of a matrix

matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

result = matrix - matrix.mean(axis=1, keepdims=True, dtype = int)

print("Original Matrix:\n", matrix)
print("\nRow Means:\n", matrix.mean(axis=1, keepdims=True))
print("\nResult Matrix (Centered):\n", result)

Original Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Row Means:
 [[20.]
 [50.]
 [80.]]

Result Matrix (Centered):
 [[-10   0  10]
 [-10   0  10]
 [-10   0  10]]


In [20]:
# Q.6 Considering two arrays with shape (1,3) and (3,1), how to compute
# their sum using an iterator?

A = np.array([[11, 22, 33]]) 
B = np.array([[10], 
              [20], 
              [30]])
print(A)
print(B)

[[11 22 33]]
[[10]
 [20]
 [30]]


In [21]:
result = np.zeros((3,3), dtype = int)
for i in range(3):
    for j in range(3):
        result[i, j] = A[0, j] + B[i, 0]

print(result)

[[21 32 43]
 [31 42 53]
 [41 52 63]]


In [23]:
# Q.7 How to swap two rows of an array?
arr = np.array([[1,2,3],[10,20,30]])
print(arr)
# arr[0,::] = arr[1,::]
arr[[0, 1]] = arr[[1, 0]]
print(arr)

[[ 1  2  3]
 [10 20 30]]
[[10 20 30]
 [ 1  2  3]]


In [24]:
# Q.8 How to find the most frequent value in an array?
arr = np.array([1, 3, 2, 8, 3, 3, 2, 1, 3, 8])

counts = np.bincount(arr)

most_frequent = np.argmax(counts)

print("Array:", arr)
print("Most frequent value:", most_frequent)

Array: [1 3 2 8 3 3 2 1 3 8]
Most frequent value: 3


In [26]:
# Q.9 Given a two dimensional array, how to extract unique rows?
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]]


In [27]:
unique_rows = np.unique(arr, axis=0)

print("\nUnique Rows:")
print(unique_rows)


Unique Rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# Q.10 Extract last row of a 2D array
arr = np.arange(1,13).reshape(6,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [31]:
lr = arr[-1, ::]
print(lr)

[11 12]
