In [1]:
# 1. Create a 2D array with 1 on border and 0 on inside.

import numpy as np

In [5]:
arr = np.ones((10,10), dtype = int)
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [6]:
arr[1:-1, 1:-1] = 0 
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [12]:
# Find indices of Non-zero elements from A[2,3,0,1,0,9].
A = np.array([2,3,0,1,0,9])
arr = np.nonzero(A)
print(arr)
print(A[arr])

(array([0, 1, 3, 5]),)
[2 3 1 9]


In [17]:
# Create a zero one D vector of size 10 but 5 th indexing value should be replaced by 9.
Arr = np.zeros(10, dtype = int)
Arr[5] = 9
print(Arr)

[0 0 0 0 0 9 0 0 0 0]


In [23]:
# Create a 3×3 NumPy array of all True.
arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [24]:
# Create a 4×4 array and extract its first row and last column.
arr = np.arange(1,17)

In [25]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [28]:
arr = arr.reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [33]:
print(arr[0, :])
print(arr[:, -1])

[1 2 3 4]
[ 4  8 12 16]


In [39]:
A = np.random.randint(1,10, size = 9)
print(A)

[4 2 1 8 2 2 2 5 2]


In [40]:
np.sort(A)[::-1]

array([8, 5, 4, 2, 2, 2, 2, 2, 1], dtype=int32)