In [1]:
import numpy as np
import pandas as pd

In [3]:
arr = np.arange(1,10).reshape(3,3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr.ndim

2

In [6]:
arr2 = np.array([[[1,2,3],[4,5,6]]])
print(arr2)
arr2.ndim

[[[1 2 3]
  [4 5 6]]]


3

In [11]:
zero = np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
one = np.ones((4,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [17]:
arr = np.array([100,200,300,400])
print(arr[-1])

400


In [18]:
matrix = np.array([[11,22,33],[21,22,23]])
print(matrix)

[[11 22 33]
 [21 22 23]]


In [19]:
print(matrix[1,2])

23


In [20]:
print(matrix[1,2])
#slicing

23


In [21]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [22]:
print(arr[1:4])

[20 30 40]


In [23]:
print(arr[0:2])

[10 20]


In [24]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [32]:
print(mat[:, 1])

[2 5]


In [35]:
print(mat[1,:])

[4 5 6]


In [36]:
arr = np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


In [37]:
print(arr[::2])

[ 2  6 10]


In [40]:
indices = np.array([0,1,4])

In [41]:
print(arr[indices])

[ 2  4 10]


In [42]:
np.sort(arr)

array([ 2,  4,  6,  8, 10])

In [48]:
arr = np.array([5,2,8,1])
for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] > arr[j]:
            arr[i], arr[j] = arr[j], arr[i]

print("Sorted array:", arr)

Sorted array: [1 2 5 8]


In [50]:
arr = np.array(['ankit','sumit','amit','bittu'])
for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] > arr[j]:
            arr[i], arr[j] = arr[j], arr[i]

print("Sorted array:", arr)

Sorted array: ['amit' 'ankit' 'bittu' 'sumit']
