In [1]:
import numpy as np
n=np.array([10,20,30,40,50,60,70,80])

In [2]:
print(n[:4])


[10 20 30 40]


In [3]:
print(n[4:2])

[]


In [4]:
print(n[4:])

[50 60 70 80]


In [5]:
print(n[:4:3])

[10 40]


In [8]:
print(n[-1:])

[80]


In [9]:
print(n[-4:])

[50 60 70 80]


In [10]:
print(n[-6:])

[30 40 50 60 70 80]


In [11]:
print(n[-3:-1])

[60 70]


In [12]:
print(n[-8:])

[10 20 30 40 50 60 70 80]


In [13]:
print(n[:6:2])

[10 30 50]


In [14]:
print(n[:-6:-2])

[80 60 40]


In [15]:
print(n[:-3:2])

[10 30 50]


In [16]:
print(n[:-5:-1])

[80 70 60 50]


In [17]:
print(n[:-5:-3])

[80 50]


In [18]:
print(n[:-5:3])

[10]
